# XcodeGen config - run `xcodegen` to generate NotificationSummarizer.xcodeproj
# Install: brew install xcodegen

name: NotificationSummarizer
options:
  bundleIdPrefix: com.notificationsummarizer
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  NotificationSummarizer:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: NotificationSummarizer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notificationsummarizer.app
        INFOPLIST_FILE: NotificationSummarizer/Info.plist
        CODE_SIGN_ENTITLEMENTS: NotificationSummarizer/NotificationSummarizer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
    dependencies: []
